### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.BufferedWriter.write(java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by zwsunny** [HauyuChen/TCP-Tester#1]
you are very nice, thank you for your code ,when I run the ClientActivity project, this question is coming, Can you help me ?

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.android_tcp, PID: 16311
    java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.BufferedWriter.write(java.lang.String)' on a null object reference
        at com.example.android_tcp.MainActivity.send(MainActivity.java:146)
        at com.example.android_tcp.MainActivity$2.onClick(MainActivity.java:66)
        at android.view.View.performClick(View.java:6291)
        at android.view.View$PerformClick.run(View.java:24931)
        at android.os.Handler.handleCallback(Handler.java:808)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7425)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by YenRen** [comment]
send msg should be new Thread
